# Generated by Django 5.1.4 on 2026-06-30 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_trainerprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('points', models.PositiveIntegerField(default=10)),
                ('badge_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('special', 'Special'), ('story', 'Story')], max_length=50)),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_items', models.JSONField(blank=True, default=dict)),
                ('reward_pokemon', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.IntegerField(default=-1)),
                ('rarity', models.CharField(default='Common', max_length=50)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='avatar',
            field=models.CharField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', max_length=255),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='battles_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='current_rank',
            field=models.CharField(default='Bronze', max_length=50),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='region',
            field=models.CharField(default='Kanto', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BattleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=120)),
                ('arena', models.CharField(max_length=120)),
                ('weather', models.CharField(max_length=120)),
                ('battle_type', models.CharField(default='wild', max_length=50)),
                ('winner', models.CharField(max_length=120)),
                ('loser', models.CharField(max_length=120)),
                ('xp_gained', models.PositiveIntegerField(default=0)),
                ('coins_gained', models.PositiveIntegerField(default=0)),
                ('battle_duration', models.PositiveIntegerField(default=0)),
                ('pokemon_used', models.JSONField(blank=True, default=list)),
                ('moves_used', models.JSONField(blank=True, default=list)),
                ('items_used', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_records', to='users.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BattleStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_hits', models.PositiveIntegerField(default=0)),
                ('super_effective', models.PositiveIntegerField(default=0)),
                ('accuracy_hits', models.PositiveIntegerField(default=0)),
                ('accuracy_total_shots', models.PositiveIntegerField(default=0)),
                ('damage_dealt', models.PositiveIntegerField(default=0)),
                ('damage_taken', models.PositiveIntegerField(default=0)),
                ('healing', models.PositiveIntegerField(default=0)),
                ('pokemon_fainted', models.PositiveIntegerField(default=0)),
                ('items_used', models.PositiveIntegerField(default=0)),
                ('turns', models.PositiveIntegerField(default=0)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_stats', to='users.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CapturedPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.CharField(blank=True, default='', max_length=50)),
                ('pokedex_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('rarity', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('hp', models.PositiveIntegerField()),
                ('max_hp', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
                ('special_attack', models.PositiveIntegerField()),
                ('special_defense', models.PositiveIntegerField()),
                ('nature', models.CharField(default='Hardy', max_length=50)),
                ('ability', models.CharField(default='Overgrow', max_length=50)),
                ('moves', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(max_length=255)),
                ('shiny', models.BooleanField(default=False)),
                ('is_in_party', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_pokemons', to='users.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('coins_spent', models.PositiveIntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.trainerprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_user1', to='users.trainerprofile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_user2', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='users.trainerprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='KingdomMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='locked', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('gyms', models.PositiveIntegerField(default=0)),
                ('legendary_count', models.PositiveIntegerField(default=0)),
                ('completed_gyms', models.JSONField(blank=True, default=list)),
                ('story_progress', models.JSONField(blank=True, default=dict)),
                ('hidden_locations', models.JSONField(blank=True, default=list)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'region_id')},
            },
        ),
        migrations.CreateModel(
            name='MissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('required_progress', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mission')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='TrainerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='TrainerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('max_stack', models.PositiveIntegerField(default=99)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'item_name')},
            },
        ),
    ]
