# Generated by Django 5.1.4 on 2026-07-01 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_achievement_adminannouncement_mission_shopitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('weekly', 'Weekly'), ('seasonal', 'Seasonal'), ('limited', 'Limited-Time')], default='limited', max_length=50)),
                ('reward_type', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='battle_pass_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='battle_pass_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='crystals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='login_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('earned_from', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Claimed', max_length=50)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_history', to='users.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_claims', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='EventRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='users.event')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_claims', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'event')},
            },
        ),
        migrations.CreateModel(
            name='LevelRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_claims', to='users.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'level')},
            },
        ),
    ]
