# Generated by Django 5.1.4 on 2026-07-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_event_trainerprofile_battle_pass_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='coins_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='crystal_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(default='Common', max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='target_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='achievement',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerachievement',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
